"===================================================================================
"  FILE:  			.vimrc
"  DESCRIPTION:  this file contains my personal configuration of vimrc
"  AUTHOR:  		M. KOUROUMA
"  CREATED:  		09.09.2016
"===================================================================================
"
"*****************************
"	GENERAL SETTINGS
"*****************************
"
"" VIM
set nocompatible									" Use Vim settings, rather then Vi settings.
													" This must be first, because it changes
													" other options
													" as a side effect.
"install vim plug									" curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
													"    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

"" PLUGINS
call plug#begin('~/.vim/plugged')					"  Specify a directory for plugins and initilize

Plug 'mileszs/ack.vim'								" search in vim
Plug 'sukima/xmledit'                				" xml documents completion and tag jumping
Plug 'preservim/nerdtree'							" nerdtree for exploration
Plug 'preservim/nerdcommenter'						" comment lines,  functions,  blocks ...
Plug 'vim-airline/vim-airline'						" Lean & mean status/tabline for vim that's light as air.
Plug 'vim-airline/vim-airline-themes'				" airline themeg
Plug 'altercation/vim-colors-solarized' 			" Solarized color scheme for vim
Plug 'junegunn/fzf', {'do': { -> fzf#install() } }  "Ensure we have latest fzf
Plug 'junegunn/fzf.vim'								" fzf love vim
Plug 'prabirshrestha/async.vim'						" async jop control
Plug 'prabirshrestha/vim-lsp'						" vim-lsp
Plug 'mattn/vim-lsp-settings'						" easy  setup language servers using vim-lsp
Plug 'bfrg/vim-cpp-modern'							" Enhanced C and C++ syntax highlighting
Plug 'prabirshrestha/asyncomplete.vim'				" auto-completion with asyncomplete
Plug 'prabirshrestha/asyncomplete-lsp.vim'  		" LSP source for asyncomplete.vim and vim-lsp
Plug 'SirVer/ultisnips'								" Snippets engine
Plug 'honza/vim-snippets' 							" snippets
Plug 'thomasfaingnaert/vim-lsp-snippets'			" snippets integration in vim-lsp
Plug 'thomasfaingnaert/vim-lsp-ultisnips'			" ultispnips integration in vim-lsp
Plug 'psf/black'									" black plugin for python code formating
Plug 'ludovicchabant/vim-gutentags'					" vim tags files managements
Plug 'skywind3000/gutentags_plus'					" works with gutentags and provides seemless databases switching
Plug 'liuchengxu/vim-which-key'						" displays available keybindings in popup
Plug 'liuchengxu/vista.vim'							" View and search LSP symbols,  tags in Vim/NeoVim.
"Plug 'neoclide/coc.nvim',  {'branch': 'release'}	" conquerer of completion
Plug 'tpope/vim-fugitive'							" Fugitive is the premier Vim plugin for Git.
Plug 'mbbill/undotree'								" visualizes undo history
Plug 'vhda/verilog_systemverilog.vim'				" Syntax Plugin for Verilog and SystemVerilog
Plug 'airblade/vim-gitgutter'						" A Vim plugin which shows a git diff in the sign column
call plug#end()										" Initialize plugin system
"
"
"********************
" extra env settings
"********************
"
source ~/.env/vim/settings.vim
source ~/.env/vim/commands.vim
source ~/.env/vim/mapping.vim

