# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

path+=($HOME/.env/bin)
path+=(/opt/nvim-linux64/bin)
path+=(~/.local/bin)
#path+=(/opt/modelsim/modeltech/linux_x86_64)
export PATH
export ZSH="$HOME/.oh-my-zsh"
#ZSH_THEME="agnoster"
# install powerlevel10k
#git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(fzf git krm ssh-agent sqn tmux web-search)
source $ZSH/oh-my-zsh.sh
#export TERM=screen-256color-bce
export EDITOR='vim'
# Dir: current working directory
#prompt_dir() {
  #prompt_segment blue $CURRENT_FG '%~'
  #prompt_segment blue $CURRENT_FG '%c'
#}
#modelsim
#export MGLS_LICENSE_FILE="/opt/modelsim/10.7/win64/license.dat"
#export LM_LICENSE_FILE="/opt/modelsim/10.7/win64/license.dat"




# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
