path+=($HOME/.env/bin)
path+=(/opt/modelsim/modeltech/linux_x86_64)
export PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
plugins=(fzf git krm ssh-agent sqn tmux web-search)
source $ZSH/oh-my-zsh.sh
#export TERM=screen-256color-bce
export EDITOR='vim'
# Dir: current working directory
prompt_dir() {
  #prompt_segment blue $CURRENT_FG '%~'
  prompt_segment blue $CURRENT_FG '%c'
}
#modelsim
#export MGLS_LICENSE_FILE="/opt/modelsim/10.7/win64/license.dat"
#export LM_LICENSE_FILE="/opt/modelsim/10.7/win64/license.dat"
export LM_LICENSE_FILE="/home/kourouma/intelFPGA/21.1/questa_fse/LR-095811_License.dat"


