path+=($HOME/.env/bin)
export PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
plugins=(fzf git krm ssh-agent sqn tmux web-search)
source $ZSH/oh-my-zsh.sh
#export TERM=screen-256color-bce
export EDITOR='vim'

